name: Quick Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  quick-test:
    name: Quick Test and Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
    
    - name: Set up Python
      run: uv python install 3.12
    
    - name: Install dependencies
      run: uv sync
    
    - name: Install package
      run: uv pip install -e .
    
    - name: Test basic CLI functionality
      run: |
        uv run excludarr --help
        uv run excludarr --version
        uv run excludarr providers list --popular
    
    - name: Run unit tests (core modules only)
      run: uv run pytest tests/test_tmdb_client.py tests/test_simple_cache.py tests/test_config.py -v
    
    - name: Test package build
      run: uv build
    
    - name: Verify package contents
      run: |
        ls -la dist/
        uv run python -c "import excludarr; print(f'excludarr version: {excludarr.__version__}')"